### ISSUE TITLE
Left Navigation Scrollbar Missing

### ISSUE THREAD

**Issue by wwfiserv** [Fiserv/Support#139]
# Reporting new issue for Commerce Hub

**Page**
All Pages

**Describe the bug**
When navigating Dev Studio on the navigation bar is not available to scroll until you use the scroll wheel on the mouse. If you hover over the side where the scroll bar should be it isn't available. Once you scroll with a mouse wheel then it displays the scroll bar. This makes it nonfunctional on track pads and similar devices.

**Expected behavior**
Scroll bar for navigation pane should always be available when you hover over the section where is displayed, not just after you attempt to scroll with a mouse wheel.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by sfiserv** [comment]
This is an intended functionality implemented for Devtudio. Please refer this JIra for details
https://firstdatateam.atlassian.net/browse/PORT-3440

**Comment by wwfiserv** [comment]
@sfiserv I think you misunderstood the request, it's not that we don't like the slim scrollbar from PORT-3440, it's the fact that the thin scrollbar doesn't appear until you actually scroll. If you don't have a scroll wheel or know how to perform this on a trackpad this is not possible.

**Comment by sfiserv** [comment]
@wwfiserv we have created another ticket for this issue 
 https://firstdatateam.atlassian.net/browse/PORT-4806

**Comment by sfiserv** [comment]
This issue has been addressed and implemented in Sprint16  https://firstdatateam.atlassian.net/browse/PORT-4806
hence closing this issue

**Comment by wwfiserv** [comment]
Problem still exists, these should only be closed by the individual who opened the ticket confirms here is what I'm still getting in Dev 
![image](https://user-images.githubusercontent.com/75692745/184405854-bbe05568-94aa-4b82-bd19-2d9dd2f0fc0e.png)

Again the issue occurs when data is beyond the screen height, example and expanded element and you navigate to the page for the first time. Once you scroll in the left nav it will work, however if you leave the product for example to search and come back it will not have the scroll visible until you scroll again with the mouse wheel or the touchpad scroll function.

**Comment by sfiserv** [comment]
We had a call with William to understand the steps to recreate and the issue is seen only on Windows machine . Hence we have to disable the smart scrolling.

**Comment by TaniaSarkar89** [comment]
Closing this issue since no confirmation received.
