### ISSUE TITLE
I can't create a Banking Hub workspace [TX ID: 50a674c4-e7f2-4fa0-b6ca-9ecc25296733]

### ISSUE THREAD

**Issue by bfreudenberg** [Fiserv/Support#374]
I am trying to create a Banking Hub workspace, but it isn't working.  Commerce Hub workspace is working, but not Banking Hub.  Looks like you had this issue reported yesterday, but I'm having the issue today.  Is this something wrong in my profile, or something wrong on your side?

**Comment by bfreudenberg** [comment]
Still not working today.

**Comment by bfreudenberg** [comment]
Still not working today.  Does anyone monitor this bug listing?

**Comment by sfiserv** [comment]
@bfreudenberg  Can you please check now. The Banking Hub had few issues on backend. They are now fixed and workspace creation is working fine.
Please let us know if you are facing similar issues.

**Comment by bfreudenberg** [comment]
No, it still isn't working.  Seems to be the same issue.  I know that one of the guys on my dev team tried yesterday, and it worked fine for him.  So maybe it's something with my account?  I'd really appreciate some assistance with this when you can.  We're trying to get started with Communicator Open (already a customer), but struggling a bit at this point.  Thanks.

**Comment by sfiserv** [comment]
@bfreudenberg  would you be able to send out few more information regarding the error you are seeing. Can you send our your user account email/user id on Devstudio, screenshot of the error if any.
What is the name are trying to use for the Banking hub workspace.
I can check with my team if they find any issues with your account.

**Comment by sfiserv** [comment]
@bfreudenberg  would you be able to send out few more information regarding the error you are seeing. Can you send our your user account email/user id on Devstudio, screenshot of the error if any.
What is the name are trying to use for the Banking hub workspace.
I can check with my team if they find any issues with your account.

**Comment by bfreudenberg** [comment]
My connection email is bfreudenberg@texasregionalbank.com.
I was creating a workspace named BcfTest (and I tried a bunch of other names as well).
Screenshots of the creation form, as well as the error, are in the attached Word document.
[BankHubWsCreateError.docx](https://github.com/Fiserv/Support/files/11265269/BankHubWsCreateError.docx)

**Comment by sfiserv** [comment]
@bfreudenberg our team is working with Banking hub team to check the issue with your account.
I will update here once I get more information.

**Comment by anandrewfiserv** [comment]
@bfreudenberg There is currrently a bug where the internal system does not accept a company name with spaces. We are in process of rolling out the fix. In the meantime, could you please remove the company name from the organization page and try again? Thank you.

**Comment by bfreudenberg** [comment]
That was it!  Thank you very much.  I’ve got my workspace created now.  I appreciate the help.


Brad Freudenberg
Executive Vice President
Chief Technology Officer


[TRB resized]
6770 W. Expressway 83, 3rd Floor
Harlingen, TX 78552
Office: (956) 368-5344 Ext:6044
Cell: (832) 687-3890
texasregionalbank.com<http://www.texasregionalbank.com/>
***@***.***<http://www.facebook.com/Texasregionalbank>Follow Texas Regional Bank on Facebook<http://www.facebook.com/Texasregionalbank>
