### ISSUE TITLE
API Explorer in Preview Branch is redirecting us to Active Branch 

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#402]
### Product

Banking Hub

### Page

https://qa-developer.fiserv.com/product/BankingHub/api/?type=post&path=/addrservice/partyacctsvc/address&branch=develop&version=11.0.0&tab=api_explorer

### Description

Performing some testing in qa branch, in Preview version branch whenever we select any operation for a service (say Add Address for Address Service) from API explorer, it redirects or switches to the Active version branch. It does not stay in the Preview version.

Issue reported by @GulrukhNaaz 
cc: @fiservakshay 

### Expected Behaviour

Stay on Preview branch when looking into API Explorer section.

### Operating system

Microsoft 64-bit operating system, x64-based processor

### Browser

Google Crome

**Comment by sfiserv** [comment]
@tsegurajimen please verify this issue is fixed in QA. please close the issue after verification.

**Comment by tsegurajimen** [comment]
Hi @sfiserv @anandrewfiserv  I was reviewing but issue still affecting Documentation Section, when navigating thru Documentation section dropdown changes from Preview to Active Branch, in the other hand API Explorer navigation is working as expected.

Can you please verify?

**Comment by sfiserv** [comment]
@tsegurajimen  team is checking this issue again.
cc: @anandrewfiserv

**Comment by tsegurajimen** [comment]
Preview Branch is now working as expected in Dev/QA, Stage and Prod Enviroments.

![image](https://github.com/Fiserv/Support/assets/81706748/e23361c2-5d07-48df-b0d9-29aded949c2d)

Then closing this ticket.
