### ISSUE TITLE
Extra Date-Time notation added to Date fields in the examples***

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#64]
# Reporting new issue for Integrated Banking Tenant

**Page**
https://dev-developer.fiserv.com/product/IntegratedBanking/api/?type=post&path=/stopChecks)

**Describe the bug**
In the examples added for all Open Banking APIs, the UI displays that all date-time and date fields are being modified, showing additional date-time notation at the end.

For example this is how the Request example for Stop Check Add is saved in the Cards_Merged_Spec-11.0.0.yaml (merged file) used by the portal:

![image](https://user-images.githubusercontent.com/81706748/143480742-2693bfd4-bce9-470d-8b27-c913e2ba1c6f.png)

In the other hand this is how the same example is being displayed in the portal:

![image](https://user-images.githubusercontent.com/81706748/143480876-21db69ce-7694-439a-ae73-17eb95d62e6e.png)

If we try to run the message. it returns a 422 due to the fields: OrigDt, StopChkDt and ExpDt are defined as Date fields in the specification, not as Date-Time.

![image](https://user-images.githubusercontent.com/81706748/143481124-7db3c227-f2fa-47d7-aca4-b7cca0492f71.png)

Prism Logs:

![image](https://user-images.githubusercontent.com/81706748/143481163-716fab66-d3db-4d44-8d03-fb69864e8e45.png)

**To Reproduce**
1. Go to (https://dev-developer.fiserv.com/product/IntegratedBanking/api/?type=post&path=/stopChecks)
2. Click on Premier Example
3. Click Run
4. See error 422

**Expected behavior**
201 Response as follows:

![image](https://user-images.githubusercontent.com/81706748/143481343-7009e2aa-5a23-4cb6-a26e-3ea2db013f69.png)

- Assign a Bug to: @acho-fiserv 

- Adding @fiservakshay, @brittaho and @bobburghardt for awareness.

**Comment by tsegurajimen** [comment]
Following fields were updated to date time on POST /stopChecks and POST /parties/secured/list to avoid issues while issue is fixed.
/parties/secured/list : Default - 200 (Dev Portal Issue to be solved)
  "BirthDt": "1991-11-20T00:00:00.000Z", - Change schema definition*** Wait for fix on January

/stopChecks : Default - 200 (Dev Portal Issue to be solved)
  "OrigDt": "2021-11-20T00:00:00.000Z", - Change schema definition*** Wait for fix on January
  "StopChkDt": "2021-11-20T00:00:00.000Z", - Change schema definition*** Wait for fix on January
  "ExpDt": "2021-11-20T00:00:00.000Z", - Change schema definition*** Wait for fix on January

![image](https://user-images.githubusercontent.com/81706748/146275408-8afb1dc8-8bf3-429b-a850-00ad7b8050c5.png)

**Comment by jimmychen-fiserv** [comment]
This is been fixed. Please test.

**Comment by tsegurajimen** [comment]
Performing some testing we realized that extra date-time notation was cleaned from the default view and it is working fine, but additional examples in the API still displaying the extra date time notation what is causing the example fails:

Default View:
![image](https://user-images.githubusercontent.com/81706748/149382317-7942e1eb-1078-4eee-a80a-88d3e5b00fc6.png)

Sample View:
![image](https://user-images.githubusercontent.com/81706748/149382358-0efbbedd-4e13-459e-abfb-651034a3be81.png)

![image](https://user-images.githubusercontent.com/81706748/149382377-adaba849-bdc2-4b33-a74e-20a846bb7b3c.png)

![image](https://user-images.githubusercontent.com/81706748/149382481-1c362237-84d6-4865-a325-906117313693.png)

Regards,

**Comment by rajeshb15** [comment]
This issue is resolved and working as expected.
https://dev-developer.fiserv.com/product/IntegratedBanking/api/?type=post&path=/stopChecks

![image](https://user-images.githubusercontent.com/80118847/150406491-6134f55f-9898-454a-97f7-e5292fb3225a.png)

**Comment by tsegurajimen** [comment]
Hi Team,

@acho-fiserv  @rajeshb15 @OZ

Please your help because this issue is not resolved yet, extra date-time notation is being displayed in the samples, default view was fixed as you show in the screenshot but samples still displaying extra date-time notation for fields that are date only.

![image](https://user-images.githubusercontent.com/81706748/150860771-d3e3dd53-33f6-4eea-bece-1af1442dd2b2.png)


cc: @fiservakshay 
Thanks in advance for your help!

**Comment by TaniaSarkar89** [comment]
Opened a JIRA ticket : https://firstdatateam.atlassian.net/browse/PORT-3192

**Comment by rajeshb15** [comment]
@tsegurajimen 
1. If your datatype is Date then we do mot need to enclose in quotes
2. If your datatype is string it should be in quotes

![image](https://user-images.githubusercontent.com/80118847/152585395-b8e339b7-6145-4ec7-8cd2-17d126c5ed5a.png)

**Comment by tsegurajimen** [comment]
Hi @rajeshb15 ,

The thing is that at the end both are string fields, remember that how that data type is defined in SwaggerHub is:
type: string
format: date
That's why when we export it as "yaml Resolved" it adds the quotes to dates fields as well.

![image](https://user-images.githubusercontent.com/81706748/152602649-0aead462-2321-4c88-8a8c-b2d851048b1c.png)

Also another important thing is if we removed the quotes the mock server will fail because it validates the fields as String/Date.

Regards,

**Comment by rajeshb15** [comment]
@tsegurajimen 
We need quotes and the format should be like below:
```
- OpenDt: '2017-05-05' //will be as is
```
And the following format will result date serialization.
`- OpenDt1: 2017-05-05  //will be converted into full JS-Date`

**Comment by tsegurajimen** [comment]
@rajeshb15 got it, let me check with the tech writer team on Monday and get back to you on that.

Thanks a lot!

**Comment by tsegurajimen** [comment]
Thanks @TaniaSarkar89 and @rajeshb15 for all your help, now we are looking for the best way to extract the specs as yaml resolved keeping the quotes in place to avoid the portal recognize the date fields as date-time. Thanks again!
