### ISSUE TITLE
Unable to setup password

### ISSUE THREAD

**Issue by VasuGopisetti** [Fiserv/Support#648]
### Product

Commerce Hub

### Page

Account --> Change Password

### Description

After the account was created, I did not receive the temporary password email. So tried to reset the password using one-time passcode; this time received an email with passcode but was unable to set the password. I am seeing a screen where it says we are experiencing technical difficulties.

### Expected Behaviour

I should be able to create/update my password

### Operating system

Windows 11

### Browser

Google Chrome 122.0.6261.129

### Region

India

**Comment by minh-pham1** [comment]
Hello @VasuGopisetti! Sorry about this issue, it seems that due to some configuration changes our account creation process was down for a while. It should now be fixed, please try again (either with creating a new account or using the `Forgot Password` functionality to generate a new OTP + password for your account.

Again, apologies for the inconvenience and please let us know if there is still an issue!

**Comment by VasuGopisetti** [comment]
Hey hi minh, The issue is still the same. It says, "The one-time passcode is incorrect, or the new password does not meet requirements.". I am trying to reset the password using the Reset button available in the email, so the one-time passcode is auto-populated and the password is meeting all the criteria, but I am still unable to set the password. Please refer to the attached screenshot.
![commerceHub](https://github.com/Fiserv/Support/assets/72455295/1c0c0b51-d066-493c-b1ba-b93f9b3eb23f)

**Comment by VasuGopisetti** [comment]
The issue is resolved after manually typing the one time passcode.

**Comment by minh-pham1** [comment]
I see, perhaps there is an issue when clicking on the button which adds some invisible whitespace or the URL. I'll create a bug ticket to have a developer investigate it. Thanks for finding this!
