### ISSUE TITLE
Get Safe Deposit Box API not displaying Request Schema and default sample 

### ISSUE THREAD

**Issue by tsegurajimen** [Fiserv/Support#70]
# Reporting new issue for Integrated Banking

**Page**
https://dev-developer.fiserv.com/product/IntegratedBanking/api/?type=post&path=/safedepositbox/secured

**Describe the bug**
Inside Safe Deposit Box Service, the Get Safe Deposit Box API is not being displayed correctly as expected, request schema and default sample are not displayed:

![image](https://user-images.githubusercontent.com/81706748/145310567-765d4e48-422b-4473-9b90-dd1a27c38365.png)

**Work around:**
We worked with @TaniaSarkar89 trying to fix it and we noticed this was a reference that was in an allOf code that was not being rendered right, so as a temporary solution we have added the code directly, dropping the reference as follows:

![image](https://user-images.githubusercontent.com/81706748/145310780-d8a046ac-ef69-450a-88e0-d387064cd237.png)
 

**Expected behavior**
To be displayed as follows:
![image](https://user-images.githubusercontent.com/81706748/145310836-fbb7dba7-0235-4d59-a8ec-ab49646a9e27.png)

Adding @fiservakshay and @brittaho for notifications.

**Comment by tsegurajimen** [comment]
As a temporary solution we changed the code of our API, replacing the allOf code while the issue is solved by the Dev Portal's Team.

**Comment by TaniaSarkar89** [comment]
Hi @tsegurajimen this issue has been resolved. Attaching the screenshots from dev env for your reference.
![image](https://user-images.githubusercontent.com/74629095/150400763-8ed12033-d41c-4980-9e41-d78abd6ab87c.png)

**Comment by tsegurajimen** [comment]
Hi @TaniaSarkar89 and team. 

This issue stills in place, the code was changed for the 20th Release but changing our code back as it was with the all of + $ref in place, not still not working:

![image](https://user-images.githubusercontent.com/81706748/150873123-705250e6-0c63-49d3-9764-ce6a3e9801ad.png)

Thanks in advance for your help!

**Comment by tsegurajimen** [comment]
In addition we found a similar issue in Stop Check Service, Add Stop Check, where the **FromAcctKeys** is displayed as an object not displaying the properties accordingly as it were displayed right before:

https://dev-developer.fiserv.com/product/BankingHub/api/?type=post&path=/stopChecks

![image](https://user-images.githubusercontent.com/81706748/150873380-9a5a3cea-80b2-4b85-870d-9f8b599c6f18.png)

This issue is also causing the Default example fails, because the properties of the object are not displayed:

![image](https://user-images.githubusercontent.com/81706748/150873557-4a0660c7-0f27-453d-94ed-f47be018351f.png)

![image](https://user-images.githubusercontent.com/81706748/150873532-e743a4e2-c180-4bc8-86ef-cd0292e642ca.png)

Thanks again for your help!

**Comment by tsegurajimen** [comment]
Issue is now fixed for both messages that were affected:

https://dev-developer.fiserv.com/product/BankingHub/api/?type=post&path=/safedepositbox/secured
![image](https://user-images.githubusercontent.com/81706748/151222682-887f0acb-7e70-48ef-9bf8-ea720d2ffb49.png)

https://dev-developer.fiserv.com/product/BankingHub/api/?type=post&path=/stopChecks
![image](https://user-images.githubusercontent.com/81706748/151223229-c0629ba4-1992-4d01-9782-431b030dadc6.png)

Thanks a lot!
